### ISSUE TITLE
Add document template for Supplement

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-templates-itu#2]
[ITUT-Supp-Skelet.docx](https://github.com/metanorma/mn-templates-itu/files/3886490/ITUT-Supp-Skelet.docx)

**Comment by ronaldtse** [comment]
`:doctype: recommendation-supplement`

**Comment by ronaldtse** [comment]
Linked to https://github.com/metanorma/metanorma-itu/issues/143

**Comment by manuelfuenmayor** [comment]
@ronaldtse I think this is added and merged to master already (under `:doctype: supplement`). But perhaps would be good to re-check the existing template, @anermina?

**Comment by manuelfuenmayor** [comment]
> I think this is added and merged to master already (under :doctype: supplement).

Ah, the correct doctype value is `recommendation-supplement` as @ronaldtse said. Correcting...

**Comment by manuelfuenmayor** [comment]
PR added in https://github.com/metanorma/mn-templates-itu/pull/19

**Comment by anermina** [comment]
@manuel489 It was originally converted as `:doctype: recommendation-supplement` (https://github.com/metanorma/mn-samples-itu/pull/56/commits). I don't know why it was changed later. However, `recommendation-supplement` is also valid according to metanorma.com, so I think your PR should stay active.

**Comment by anermina** [comment]
Since this document is converted and merged, I'm closing this issue.

**Comment by manuelfuenmayor** [comment]
@anermina, got it! Thanks!

**Comment by opoudjis** [comment]
Note, I'm updating the template in the light of https://github.com/metanorma/metanorma-itu/issues/143, and inspection of both the doc template (which has the same draft template form as for technical reports), and published supplement ITU-T L.Sup37.
