### ISSUE TITLE
Update resolution template

### ISSUE THREAD

**Issue by opoudjis** [metanorma/mn-templates-itu#26]
In light of changes in:

* https://github.com/metanorma/metanorma-itu/issues/133
* as documented in https://github.com/metanorma/metanorma.com/compare/doc20201230
* and as illustrated with markup updates in https://github.com/metanorma/mn-samples-itu/commit/fd89bace0448fff8073ddc67349acade8aa373e5

**Comment by manuelfuenmayor** [comment]
Changes are ready to review in https://github.com/metanorma/mn-templates-itu/pull/27

**Comment by opoudjis** [comment]
A-OK

**Comment by manuelfuenmayor** [comment]
Changes approved and merged. Closing.
