### ISSUE TITLE
Add document for Implementer's Guide

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-templates-itu#3]
[Implementers_Guides.docx](https://github.com/metanorma/mn-templates-itu/files/3886491/Implementers_Guides.docx)

**Comment by manuelfuenmayor** [comment]
Added in https://github.com/metanorma/mn-templates-itu/pull/8

**Comment by ronaldtse** [comment]
Linked to https://github.com/metanorma/metanorma-itu/issues/144
