### ISSUE TITLE
Add document template for Technical Paper

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-templates-itu#4]
[Technical_Paper.docx](https://github.com/metanorma/mn-templates-itu/files/3886492/Technical_Paper.docx)

**Comment by manuelfuenmayor** [comment]
Added in https://github.com/metanorma/mn-templates-itu/pull/9

**Comment by ronaldtse** [comment]
Linked to https://github.com/metanorma/metanorma-itu/issues/145
