### ISSUE TITLE
Add document template for Technical Report

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/mn-templates-itu#5]
[Technical_Report.docx](https://github.com/metanorma/mn-templates-itu/files/3886495/Technical_Report.docx)

**Comment by ronaldtse** [comment]
Linked to https://github.com/metanorma/metanorma-itu/issues/146

**Comment by anermina** [comment]
Converted in https://github.com/metanorma/mn-templates-itu/pull/11 and merged. Closing.
