### ISSUE TITLE
ITU-T Supplement: Rendering angle brackets 

### ISSUE THREAD

**Issue by anermina** [metanorma/mn-templates-itu#7]
ITU-T supplement requires using angle brackets (i.e. < and >), but they cannot be rendered properly using:
1. only < and >
2. balanced and unbalanced escape characters before < and/or >
3. re-using text declared as a document attribute (even with escape characters, etc.)
4. passthrough (+ characters before < and after >)

Is there an alternative?

Rendered:
![image](https://user-images.githubusercontent.com/55683568/69674448-c7b9b300-109c-11ea-8f04-feb17fb0ae23.png)

[angle_brackets.zip](https://github.com/metanorma/mn-templates-itu/files/3894111/angle_brackets.zip)

**Comment by opoudjis** [comment]
Wow. All of these are ending up in the XML as literal `<`, and they need to end up as `&lt; &gt;`.

**Comment by opoudjis** [comment]
If I parse the document as standoc, the < are correctly left as `&lt;`. Ditto ISO. 

So something in ITU is preemptively rendering the escapes.

**Comment by opoudjis** [comment]
It's the routine that replaces smart quotes with dumb, which is specific to ITU...
